import 'package:dio/dio.dart';
import 'package:tests_system/models/question_model.dart';

Future<List<Autogenerated>> getQuiz() async {
  Dio req = Dio();
  Response response =
      await req.get("https://66564cc59f970b3b36c4ef01.mockapi.io/tests");
  List<Autogenerated> quiz = List.generate(
    response.data.length,
    (index) => Autogenerated.fromJson(response.data[index]),
  );
  return quiz;
}

Future<Autogenerated> postQuiz(Autogenerated question) async {
  Dio req = Dio();
  Response response = await req.post(
    "https://66564cc59f970b3b36c4ef01.mockapi.io/tests",
    data: question.toJson(),
  );
  return Autogenerated.fromJson(response.data);
}
