class Autogenerated {
  String? questionText;
  List<String>? answers;
  String? correctAnswer;
  String? id;

  Autogenerated({this.questionText, this.answers, this.correctAnswer, this.id});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    questionText = json['questionText'];
    answers = json['answers'].cast<String>();
    correctAnswer = json['correctAnswer'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['questionText'] = this.questionText;
    data['answers'] = this.answers;
    data['correctAnswer'] = this.correctAnswer;
    data['id'] = this.id;
    return data;
  }
}
